version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ttr-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t42sipfdda7y"
s3_prefix = "ttr-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
